Add option to adjust alignment of text of multi-line values.
sciunto-org/python-bibtexparser pull request #290
Opened 2022-01-03 15:41 UTC by michaelfruth

A new option `align_multiline_values` is added to BibTexWriter to enable whether text of multiline values should be aligned on top of each other. Indentation also considered `_max_field_width`.

Current behaviour:
BibTeX entry:
```
@article{test,
  title     = {Hello World. I'm a very very very
  very very very very long title. Hello Bibtex Parser!
  This is still a long title!},
}
```

Parsing with BibtexParser will result in:
```
@article{test,
 title = {Hello World. I'm a very very very
very very very very long title. Hello Bibtex Parser!
This is still a long title!}
}
```

When `align_multiline_values` is set to true, the output will be the
following:
```
@article{test,
 title = {Hello World. I'm a very very very
          very very very very long title. Hello Bibtex Parser!
          This is still a long title!}
}
```

2022-07-09 18:14 UTC, MiWeiss commented
Hi @michaelfruth 

I just joined the project - sorry for the long wait. 

Before I start the full review - would you mind adding some unit tests to cover this functionality? Please also make sure the already existing indentation functionality works well with this.

Thanks for opening the PR!

2022-07-10 12:32 UTC, michaelfruth commented
Thanks! I'll probably add some unit tests next week or two.

2022-08-09 17:36 UTC, michaelfruth commented
I'm lacking behind my schedule. I didn't forget to write some tests, try to do this until the end of this week.

2022-08-09 17:54 UTC, MiWeiss commented
No worries! Thanks for the heads up, and for your contribution.

2022-08-09 20:15 UTC, michaelfruth commented
I've added some tests to test:
1. the basic functionality
2. the new functionality with `align_values` and `indent`

I have also encountered this behavior #315 , I'm not quite sure if this is expected.

2022-08-16 11:59 UTC, MiWeiss requested changes
lgtm. found just one tiny issue in an inline comment.

2022-08-16 11:59 UTC, MiWeiss commented on bibtexparser/bwriter.py
> +        # Align multi-line values. Formats a multi-line value such that the text is aligned exactly on top of each other.
```suggestion
        #: Align multi-line values. Formats a multi-line value such that the text is aligned exactly
        #    on top of each other. Default: False
```

Just to be consistent with the remainder of the docstring

2022-08-22 06:41 UTC, MiWeiss approved these changes
lgtm. thanks for your contribution!

2022-08-22 06:41 UTC, merged