Added option to select encoding of .bib file in parse_file()
sciunto-org/python-bibtexparser pull request #395
Opened 2023-08-31 13:58 UTC by himcraft

2023-08-31 14:01 UTC, MiWeiss commented
Thanks @himcraft for the PR. 

The code change looks good, but would you mind adding a few tests? I know that the change is rather trivial, thus the purposes of the tests would not be to verify if you change is correct (I am convinced that it is), but instead serve to prevent from regression, i.e., from unintentionally breaking this function in the future.

Thanks!

2023-08-31 16:15 UTC, himcraft commented
Added `test_encoding.py` and a `gbk_test.bib` file in `tests/`.
This is my first attempt at writing tests for a Python project. Please feel free to point out any errors or suggest improvements :)

2023-08-31 20:20 UTC, MiWeiss requested changes
Thanks a lot for your commit.

Your test would certainly already be sufficient as a regression test. I still have left some minor comments, mostly to keep the test atomic and the test organisation (read file structure) consistent with the remainder of the test suite.

Afterwards, this will be ready to be merged :rocket: Thanks!

2023-08-31 20:20 UTC, MiWeiss commented on tests/test_encoding.py
> +    lines = writer.write(library).splitlines()
I would suggest not making the assertion on the "re-written" bibtex, but on the parsed entities instead.

e.g. `assert library.entries[0]["author"] == ...`

That way, we can keep the test independent of the writer.

2023-08-31 20:20 UTC, MiWeiss commented on tests/test_encoding.py
> +"""Testing the parse_file function."""
can we re-name this file to `test_entrypoint` and the module docstring accordingly - there's likely to be added more tests to it eventually.

2023-08-31 20:20 UTC, MiWeiss commented on tests/gbk_test.bib
> +@ARTICLE{����2013,
Please move this file into a (new) `tests/resources` folder.

2023-08-31 20:21 UTC, MiWeiss commented on CONTRIBUTING.md
> +- To lint your code (required for CI/CD to pass), run: `black bibtexparser tests docs && isort bibtexparser tests docs --profile black`
Nice catch ;-)

2023-09-01 05:49 UTC, MiWeiss approved these changes
lgtm!

Thanks a lot for your contribution. If there's any more problems or missing features you spot, please do not hesitate to report them.

2023-09-01 05:50 UTC, merged